[ALLI-6738] Multiselect component
NatLibFi/NDL-VuFind-ui-components pull request #110
Opened 2022-03-15 13:02 UTC by LuomaJuha

Few tunes and stuff. Adds a multiselect component. Work might still be in progress.

2022-03-15 14:58 UTC, aleksip requested changes
Tässä on niin paljon yleisiä muutoksia, että voisi jakaa kahdeksi PR:ksi jotta saadaan selkeämmät commitit.

2022-03-15 14:58 UTC, aleksip commented on compile-config.json
> +{
Uusi config-tiedosto vähän mietityttää, mutta on siinä puolensa. Tämän voisi nimetä neutraalimmin `scripts-config.json` niin käy paremmin selville mistä kyse, eikä ota niin vahvasti kantaa toiminnallisuuteen.

Tuo on hyvä sääntö, että päätason avaimet vastaavat aina skriptin nimeä. Avaimet voisi vielä laittaa aakkosjärjestykseen.

2022-03-15 14:58 UTC, aleksip commented on compile-config.json
> +    "source/components/molecules/navigation/finna-multiselect/finna-multiselect.js"
Tähän voisi lisätä `finna-tabs-nav.js`:n ja `finna-md-editable.js`:n.

2022-03-15 14:58 UTC, aleksip commented on package.json
> +    "build:js-components": "node scripts/build-components.js",
Tämä voisi tehdä niin että on `build:js` ja `minify:js`, jota `build:js` kutsuisi.

Ideana sama kuin `build:css` joka kutsuu `build:less`:iä, ja ajatuksena on että myöhemmässä vaiheessa se kutsuisi myös `build:pcss`:ää. `build:js`:ää voi sitten tarpeen vaatiessa laajentaa samaan tapaan kutsumaan jotain muuta JS-buildissa tarvittavaa erillistä skriptiä. Ja jossain vaiheessa voisi olla myös `minify:css`.

2022-03-15 14:58 UTC, aleksip commented on scripts/assets.js
> +  console.log(`Compile-config missing assets`);
- Voisi olla 'copyAssets key missing from scripts-config.json'.
- Skriptin nimen voisi muuttaa `copy-assets.js`. Eli yritettäisiin nimetä kaikki skriptit mahdollisimman kuvaavana verbi-objektiparina. Config-avaimet olisivat sitten vastaavasti skripti camelCasena, ja npm-nimet tapauksesta riippuen joko väliviivalla `copy-assets` tai kaksoispisteellä jos kuuluu johonkin kokonaisuuteen, esim. `minify:js`
- Niinpä `less-build.js`:nkin voisi nimetä `build-less.js` ja config-avaimen `buildLess`.
- Jos avain puuttuu jatkaa silti ja buildi kaatuu virheeseen. 
- ESLint antaa pari herjaa.

2022-03-15 14:58 UTC, aleksip commented on scripts/build-components.js
> +
- Tämä voisi olla `minify-js.js`, kun buildivaiheeseen voi tulla muutakin, jonka toivottavasti saa eriytettyä omaan erikseen ajettavissa olevaan skriptiinsä.
- Skripti voisi samalla generoida skriptikohtaiset minimoidut versiot komponenttihakemistoon? Tämän voi toki tehdä myöhemminkin omassa PR:ssään.

2022-03-15 14:58 UTC, aleksip commented on scripts/build-components.js
> +  console.log(`Compile-config missing buildComponents`);
'minifyJs key missing from scripts-config.json'.

2022-03-15 14:58 UTC, aleksip commented on source/components/molecules/navigation/finna-multiselect/demo/finna-multiselect-element-demo.phtml
> +  data-clear-text="Empty selections."
"Clear all selections"

2022-03-15 14:58 UTC, aleksip commented on package.json
>      "eslint": "eslint --ignore-pattern public/js/vendor --ignore-pattern public/js/styleguide/vendor public/js",
Tähän ja `jshint`-kohtaan voisi lisätä `scripts`-hakemiston.

2022-03-16 09:30 UTC, aleksip commented on source/components/molecules/navigation/finna-multiselect/demo/finna-multiselect-element-demo.phtml
> +<?php $this->headScript()->appendFile('components/molecules/navigation/finna-multiselect/finna-multiselect.js'); ?>
Olin näemmä laittanut polkuehdotukseksi molecules/navigation mutta tälle parempi olisi molecules/forms.

2022-03-16 12:35 UTC, aleksip commented on scripts/build-components.js
> +// Ignore jshint as this does run in es8 (ES6 is only in the component library).
Ignoret voi nyt poistaa kun mergeää tähän uudet scripts-kohtaiset linttauskonfiguraatiot.

2022-06-17 06:06 UTC, aleksip commented
@LuomaJuha #114 sisältää nyt suurimman osan näistä setup-muutoksista.

JavaScriptin yhdistäminen ja minifiointi eivät välttämättä ole niin tarpeellisia, koska sekä VuFindissa että hallintaliittymässä ne tehdään omassa asset pipelinessa. Kehitysvaiheessa on puolestaan hyvä, että ovat alkuperäisessä muodossaan. Eli minifioinnin voisi melkein jättää pois, tai ainakin siirtää tästä erilliseen PR:ään, jolloin tähän jäisi vain multiselect.

2022-06-17 07:36 UTC, LuomaJuha commented
Hmm, ajatuksena oli kanssa vähän sellainen, että jos on näitä pelkkiä js-only komponentteja niin voisi minifoida sellaisen tiedoston jota pystyisi helposti sitten hyödyntämään muissa sivustoissa samaan tapaan kuin esim bootstrappia tjsp. @aleksip

2022-06-17 08:52 UTC, aleksip commented
@LuomaJuha Joo, eikä erillisestä minifiointimahdollisuudesta tosiaan varsinaista haittaakaan ole. Voihan nuo VuFindiin/hallintaliittymäänkin viedä minifioituna. Ja kehitys/PL-vaiheessakin voi käyttää minifioituja, jos tehdään sourcemapit. Hieman niiden generointi ja käyttö tietysti hidastaa, eli ehkä se voisi olla valinnainen build step. Ellei multiselectin tekeminen mene liian haastavaksi ilman, niin voisi vielä jatkaa tätä pohdintaa erillisessä minifiointi-PR:ssä?

2022-06-17 09:41 UTC, EreMaijala commented
Valmiiksi minifioidussa on se hyvä puoli ainakin VuFindin puolella, että nopeuttaa bundlen kokoamista, kun ei tartte minifioida enää siinä vaiheessa.

2022-06-17 11:09 UTC, LuomaJuha commented
@aleksip Joo, voidaan tehdä erillinen minifointipr ihmettely.

2022-06-20 13:26 UTC, pasitiis commented on source/components/molecules/forms/finna-multiselect/finna-multiselect.js
> +      multiOption.classList.add('option');
Lisää myös role-attribuutti.  multiOption.setAttribute('role', 'option');

2022-06-21 07:14 UTC, pasitiis commented
Lisää input-kenttää role="combobox" ja mahdollisesti myös aria-controls . https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/combobox_role

2022-06-21 11:42 UTC, pasitiis commented
aria-controls ei näyttäisi vaikuttavan mihinkään, joten en sitä lisäisi, eikä sitä monetkaan ruudunlukijat tue.

En tosin vielä pysty aktivoimaan listaa voiceoverilla text-inputista (ctrl + option + space). [Täällä](https://github.com/trussworks/accessibility/wiki/Combobox) listatut combobox -esimerkit näyttäisi toimivan voiceoverilla. 

Pohdin pitäsikö desc poistaa? Tuntuu vähän turhalta ul-elementin aria-labelissa.

2022-06-23 06:13 UTC, pasitiis commented
aria-activedescendant -attribuutti pitäisi kaiketi olla input-kentässä (role="combox") (luultavasti ei ratkaise voiceover-ongelmaa, varmaan tarvii vielä tarkistaa fokuksen siirtyminen eri elementtien välillä)

2022-09-01 11:52 UTC, pasitiis commented
Varmaankin tässä on parempi käyttää arian treeview-attribuutteja. Comboboxilla ei oikein saa kuvattua puurakenteen sisältö selkeästi.

2024-06-10 11:11 UTC, aleksip commented
Viedään tarvittaessa suoraan NDL-VuFind2-projektiin.

2024-06-10 11:11 UTC, closed without merging